Public Module KnownStates
    Public Function BuildKnowStatesList() As List(Of String)
        Dim states As List(Of String) = New List(Of String)
        With states
            .Add("Alabama,AL")
            .Add("Alaska,AK")
            .Add("Arizona,AZ")
            .Add("Arkansas,AR")
            .Add("California,CA")
            .Add("Colorado,CO")
            .Add("Connecticut,CT")
            .Add("Delaware,DE")
            .Add("Florida,FL")
            .Add("Georgia,GA")
            .Add("Hawaii,HI")
            .Add("Idaho,ID")
            .Add("Illinois,IL")
            .Add("Indiana,IN")
            .Add("Iowa,IA")
            .Add("Kansas,KS")
            .Add("Kentucky,KY")
            .Add("Louisiana,LA")
            .Add("Maine,ME")
            .Add("Maryland,MD")
            .Add("Massachusetts,MA")
            .Add("Michigan,MI")
            .Add("Minnesota,MN")
            .Add("Mississippi,MS")
            .Add("Missouri,MO")
            .Add("Montana,MT")
            .Add("Nebraska,NE")
            .Add("Nevada,NV")
            .Add("New Hampshire,NH")
            .Add("New Jersey,NJ")
            .Add("New Mexico,NM")
            .Add("New York,NY")
            .Add("North Carolina,NC")
            .Add("North Dakota,ND")
            .Add("Ohio,OH")
            .Add("Oklahoma,OK")
            .Add("Oregon,OR")
            .Add("Pennsylvania,PA")
            .Add("Rhode Island,RI")
            .Add("South Carolina,SC")
            .Add("South Dakota,SD")
            .Add("Tennessee,TN")
            .Add("Texas,TX")
            .Add("Utah,UT")
            .Add("Vermont,VT")
            .Add("Virginia,VA")
            .Add("Washington,WA")
            .Add("West Virginia,WV")
            .Add("Wisconsin,WI")
            .Add("Wyoming,WY")
        End With

        Return states

    End Function
End Module
